[package]
authors = ["Devon Govett <devongovett@gmail.com>"]
name = "parcel-js-swc-wasm"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
js-sys = "0.3"
parcel-js-swc-core = { path = "../core" }
serde = "1"
serde-wasm-bindgen = "0.3.0"
wasm-bindgen = "0.2"
